/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import creatie.EncryptionIni;
import creatie.Initialisatie;
import databank.DataAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zenodotus
 */
public class DlgLogin extends javax.swing.JDialog {

    private DataAdapter drm;
    private String dbGebruiker, dbWachtwoord, dbHost;
    private boolean annul = false;
    /**
     * Creates new form DlgLogin
     */
    public DlgLogin(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            if(Initialisatie.getGegeven("DBWachtwoord") == null || Initialisatie.getGegeven("DBWachtwoord").equals("")) {
                dbHost = "";
                dbGebruiker = "";
                dbWachtwoord = "";
            } else {
                dbHost = Initialisatie.getGegeven("DBHost");
                dbGebruiker = Initialisatie.getGegeven("DBGebruikersnaam");
                dbWachtwoord = EncryptionIni.decrypt(Initialisatie.getGegeven("DBWachtwoord"));
            }
            txtHost.setText(dbHost);
            txtNaam.setText(dbGebruiker);
            txtWachtwoord.setText(dbWachtwoord);
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public boolean showDialog() {
        setVisible(true);
        return annul;
                
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWachtwoord = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        btnAnnuleren = new javax.swing.JButton();

        jLabel1.setText("Naam:");

        txtNaam.setName("txtNaam"); // NOI18N
        txtNaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNaamKeyPressed(evt);
            }
        });

        jLabel2.setText("Paswoord:");

        txtWachtwoord.setName("txtPaswoord"); // NOI18N
        txtWachtwoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWachtwoordActionPerformed(evt);
            }
        });
        txtWachtwoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWachtwoordKeyPressed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.setName("btnOK"); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setName("lblFout"); // NOI18N

        jLabel3.setText("Host:");

        txtHost.setName("txtNaam"); // NOI18N
        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHostKeyPressed(evt);
            }
        });

        btnAnnuleren.setText("Annuleren");
        btnAnnuleren.setName("btnOK"); // NOI18N
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(btnAnnuleren))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(77, 77, 77))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNaam, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtWachtwoord)
                                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnAnnuleren))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWachtwoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWachtwoordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWachtwoordActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
       controle();
    }//GEN-LAST:event_btnOkActionPerformed

    private void controle() {
       try {
           String host = txtHost.getText().trim();
           String naam = txtNaam.getText().trim();
           String wachtwoord = EncryptionIni.encrypt(txtWachtwoord.getText().trim());
           if(!controleDatabank()) {
               JOptionPane.showMessageDialog(this, "Deze gebruiker is niet gekend in de databank", "Authenticatiefout", JOptionPane.ERROR_MESSAGE);
           } else {
               Initialisatie.setGegeven("DBHost", host);
               Initialisatie.setGegeven("DBGebruikersnaam", naam);
               Initialisatie.setGegeven("DBWachtwoord", wachtwoord);
               Initialisatie.opslaan();
               annul = true;
               this.setVisible(false);
           }
           
       
       } catch(Exception ex) {
           JOptionPane.showMessageDialog(this, "Er is een ernstige fout opgetreden", "coderingsfout", JOptionPane.ERROR_MESSAGE);
       }
       
    }
    private boolean controleDatabank() {
        DataAdapter dm = new DataAdapter(txtHost.getText(),
                txtNaam.getText(),
                txtWachtwoord.getText());
        if (dm.getConnection() == null) {
            return false;
        }
        return true;
    }
    private void txtWachtwoordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWachtwoordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           controle();                 
         }
    }//GEN-LAST:event_txtWachtwoordKeyPressed

    private void txtNaamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNaamKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           controle();                 
         }
    }//GEN-LAST:event_txtNaamKeyPressed

    private void txtHostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostKeyPressed

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        annul = false;
        this.setVisible(false);
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final DlgLogin dialog = new DlgLogin(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.setVisible(false);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JPasswordField txtWachtwoord;
    // End of variables declaration//GEN-END:variables
}
